import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parse } from 'yaml'
import { SiteConfigSchema } from './site-config.schema.ts'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')
const contentDir = process.env.CONTENT_DIR ?? resolve(root, '../personal-content')

const raw = parse(readFileSync(resolve(contentDir, 'site.yaml'), 'utf-8'))
const config = SiteConfigSchema.parse(raw)

// Write Nuxt app.config.ts — must live inside the app/ srcDir (Nuxt scans dirs.app/app.config)
const appConfigPath = resolve(root, 'apps/web/app/app.config.ts')
writeFileSync(
  appConfigPath,
  `// Generated by scripts/load-site-config.ts — do not edit manually\nexport default defineAppConfig(${JSON.stringify(config, null, 2)})\n`,
)

// Write generated JSON for scripts/CI reference
writeFileSync(resolve(root, 'generated/site-config.json'), JSON.stringify(config, null, 2) + '\n')

console.log('✓ site config written to apps/web/app.config.ts and generated/site-config.json')
